DROP TABLE IF EXISTS `SYS_DICTIONARY`;


CREATE TABLE `SYS_DICTIONARY` (
  `DIC_ID` VARCHAR(32) NOT NULL COMMENT '字典ID',
  `DIC_NAME` VARCHAR(50) DEFAULT NULL COMMENT '字典名字',
  `DIC_VALUE` VARCHAR(300) DEFAULT NULL COMMENT '字典值',
  `DIC_GROUP` VARCHAR(60) DEFAULT NULL COMMENT '字典分组',
  `DIC_TYPE` VARCHAR(10) DEFAULT NULL COMMENT '字典类型',
  `DIC_ORDER` INT(11) DEFAULT NULL COMMENT '字典排序',
  `DIC_STATUS` VARCHAR(10) DEFAULT NULL COMMENT '字典状态',
  `DIC_PARENT_ID` VARCHAR(32) DEFAULT NULL COMMENT '父节点ID',
  PRIMARY KEY (`DIC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
